# Generated by Django 5.2.7 on 2026-03-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='category',
            field=models.CharField(choices=[('mcqs', 'MCQs'), ('sample_paper', 'Sample Paper'), ('ncert_solutions', 'NCERT Solutions'), ('ncert_textbook', 'NCERT Textbook')], default='sample_paper', max_length=50),
        ),
    ]
