# Generated by Django 5.2.7 on 2026-03-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chapter_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='chapter',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
