# Generated by Django 5.2.7 on 2026-03-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_question_chapter_delete_chapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='category',
            field=models.CharField(choices=[('mcqs', 'MCQs'), ('sample_paper', 'Sample Paper'), ('ncert_solutions', 'NCERT Solutions'), ('ncert_textbook', 'NCERT Textbook'), ('extra_questions', 'Extra Questions'), ('previous_year', 'Previous Year Questions')], default='sample_paper', max_length=50),
        ),
    ]
