# Generated by Django 5.2.7 on 2026-04-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pdffile_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achiever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('image', models.ImageField(upload_to='achievers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
