# Generated by Django 5.2.7 on 2026-04-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_achiever'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
