# Generated by Django 5.2.7 on 2026-04-19 17:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pdffile_download_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achiever',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
