# Generated by Django 5.2.7 on 2026-04-23 19:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_achiever_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
